/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowerclient;
import javax.swing.ImageIcon;
import java.awt.event.ItemEvent;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.util.Map;
import java.awt.event.ActionEvent;
/**
 *
 * @author STD-PC
 */
public class FlowerFrame extends javax.swing.JFrame {

protected static final String[] FLOWERS = {"aster", "honeysuckle", "rose", "sunflower"};
private Map<String, Image> flowers;

    public FlowerFrame(Map<String, Image> flowers) {
        this.flowers = flowers;
        for (String flower:FLOWERS) {
        flowers.put(flower,null);
        }
            initComponents();
            
    setTitle("Garden Flowers [waiting for picture]");
    
    ItemListener rbListener = new RBListener();
    asterRadioButton.addItemListener(rbListener);
    honeysuckleRadioButton.addItemListener(rbListener);
    roseRadioButton.addItemListener(rbListener);
    sunflowerRadioButton.addItemListener(rbListener);
    
    ActionListener bListener = new ButtonListener();
    asterButton.addActionListener(bListener);
    honeysuckleButton.addActionListener(bListener);
    roseButton.addActionListener(bListener);
    sunflowerButton.addActionListener(bListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gardenFlowersPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        asterRadioButton = new javax.swing.JRadioButton();
        honeysuckleRadioButton = new javax.swing.JRadioButton();
        roseRadioButton = new javax.swing.JRadioButton();
        sunflowerRadioButton = new javax.swing.JRadioButton();
        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        mainPictureButton = new javax.swing.JButton();
        thumbnailScrollPane = new javax.swing.JScrollPane();
        thumbnailPanel = new javax.swing.JPanel();
        asterButton = new javax.swing.JButton();
        honeysuckleButton = new javax.swing.JButton();
        roseButton = new javax.swing.JButton();
        sunflowerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Pisit Kaewfung 6030213005");

        buttonGroup1.add(asterRadioButton);
        asterRadioButton.setSelected(true);
        asterRadioButton.setText("Aster");
        asterRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asterRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(honeysuckleRadioButton);
        honeysuckleRadioButton.setText("Honeysuckle");
        honeysuckleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honeysuckleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(roseRadioButton);
        roseRadioButton.setText("Rose");
        roseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roseRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(sunflowerRadioButton);
        sunflowerRadioButton.setText("Sunflower");
        sunflowerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunflowerRadioButtonActionPerformed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        mainPictureButton.setText("Waiting for picture...");
        mainPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPictureButtonActionPerformed(evt);
            }
        });
        mainPanel.add(mainPictureButton, java.awt.BorderLayout.CENTER);

        mainScrollPane.setViewportView(mainPanel);

        thumbnailPanel.setLayout(new java.awt.GridLayout(1, 0));

        asterButton.setText("Waiting...");
        thumbnailPanel.add(asterButton);

        honeysuckleButton.setText("Waiting...");
        thumbnailPanel.add(honeysuckleButton);

        roseButton.setText("Waiting...");
        thumbnailPanel.add(roseButton);

        sunflowerButton.setText("Waiting...");
        thumbnailPanel.add(sunflowerButton);

        thumbnailScrollPane.setViewportView(thumbnailPanel);

        javax.swing.GroupLayout gardenFlowersPanelLayout = new javax.swing.GroupLayout(gardenFlowersPanel);
        gardenFlowersPanel.setLayout(gardenFlowersPanelLayout);
        gardenFlowersPanelLayout.setHorizontalGroup(
            gardenFlowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScrollPane)
            .addComponent(thumbnailScrollPane)
            .addGroup(gardenFlowersPanelLayout.createSequentialGroup()
                .addComponent(asterRadioButton)
                .addGap(69, 69, 69)
                .addGroup(gardenFlowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gardenFlowersPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(honeysuckleRadioButton))
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roseRadioButton)
                .addGap(88, 88, 88)
                .addComponent(sunflowerRadioButton)
                .addContainerGap())
        );
        gardenFlowersPanelLayout.setVerticalGroup(
            gardenFlowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gardenFlowersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gardenFlowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asterRadioButton)
                    .addComponent(honeysuckleRadioButton)
                    .addComponent(roseRadioButton)
                    .addComponent(sunflowerRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thumbnailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gardenFlowersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gardenFlowersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asterRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asterRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asterRadioButtonActionPerformed

    private void honeysuckleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honeysuckleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_honeysuckleRadioButtonActionPerformed

    private void roseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roseRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roseRadioButtonActionPerformed

    private void sunflowerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunflowerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunflowerRadioButtonActionPerformed

    private void mainPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPictureButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPictureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
private class RBListener implements ItemListener {
    public void itemStateChanged(ItemEvent e) {
        showFlower();
    }
}

private class ButtonListener implements ActionListener {

    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == asterButton) asterRadioButton.setSelected(true);
        else if (e.getSource() == honeysuckleButton) honeysuckleRadioButton.setSelected(true);
        else if (e.getSource() == roseButton) roseRadioButton.setSelected(true);
        else if (e.getSource() == sunflowerButton) sunflowerRadioButton.setSelected(true);
    }
}

void showFlower() {
    Image img = null;
    if (asterRadioButton.isSelected()) {
        img = flowers.get("aster");
        if (img != null) {
            mainPictureButton.setIcon(new ImageIcon(img));
            setTitle("Garden Flowers [Aster]");
        }
    } else if (honeysuckleRadioButton.isSelected()) {
        img = flowers.get("honeysuckle");
        if (img != null) {
            mainPictureButton.setIcon(new ImageIcon(img));
            setTitle("Garden Flowers [Honeysuckle]");
        }

    } else if (roseRadioButton.isSelected()) {
        img = flowers.get("rose");
        if (img != null) {
            mainPictureButton.setIcon(new ImageIcon(img));
            setTitle("Garden Flowers [Rose]");
        }
    } else if (sunflowerRadioButton.isSelected()) {
        img = flowers.get("sunflower");
        if (img != null) {
            mainPictureButton.setIcon(new ImageIcon(img));
            setTitle("Garden Flowers [Sunflower]");
        }
    }
    if (img == null) {
        mainPictureButton.setIcon(null);
        setTitle("Garden Flowers [waiting for picture]");            
    } else mainPictureButton.setText("");
}

void setThumbnails(Map<String, Image> thumbs) {
    Image img = thumbs.get("aster");
    if (img != null) {
        asterButton.setIcon(new ImageIcon(img));
        asterButton.setText("");
    }
    img = thumbs.get("honeysuckle");
    if (img != null) {
        honeysuckleButton.setIcon(new ImageIcon(img));
        honeysuckleButton.setText("");
    }
    img = thumbs.get("rose");
    if (img != null) {
        roseButton.setIcon(new ImageIcon(img));
        roseButton.setText("");
    }
    img = thumbs.get("sunflower");
    if (img != null) {
        sunflowerButton.setIcon(new ImageIcon(img));
        sunflowerButton.setText("");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asterButton;
    private javax.swing.JRadioButton asterRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel gardenFlowersPanel;
    private javax.swing.JButton honeysuckleButton;
    private javax.swing.JRadioButton honeysuckleRadioButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainPictureButton;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JButton roseButton;
    private javax.swing.JRadioButton roseRadioButton;
    private javax.swing.JButton sunflowerButton;
    private javax.swing.JRadioButton sunflowerRadioButton;
    private javax.swing.JPanel thumbnailPanel;
    private javax.swing.JScrollPane thumbnailScrollPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
